FROM n8nio/n8n:latest

USER root

ENV DB_TYPE=sqlite
ENV N8N_PROTOCOL=https
ENV N8N_PORT=5678
ENV EXECUTIONS_DATA_PRUNE=true
ENV EXECUTIONS_DATA_MAX_AGE=168
ENV N8N_USER_FOLDER=/home/node/.n8n

EXPOSE 5678

ENTRYPOINT []
CMD ["npx", "n8n", "start"]
